extends "res://tests/social_ui.gd"

func _run() -> void:
	create_timer(120).timeout.connect(func() -> void: push_error("V27 UI TIMEOUT"); quit(1))
	_capture_prefix = "v27_1600" if "wide" in OS.get_cmdline_user_args() else "v27_1280"
	root.size = Vector2i(1600,900) if "wide" in OS.get_cmdline_user_args() else Vector2i(1280,720)
	root.content_scale_size = root.size
	_main = load("res://scenes/start.tscn").instantiate()
	_main.get_node("Bootstrap").save_path = "user://tests/v27_ui/auto.json"
	root.add_child(_main)
	_session = _main.get_node("Bootstrap").session
	var store := GhostReplayStore.new(); store.origin = _session._day.state.ghost_origin
	_session._save = store
	await _frames()
	await _click_button(_main.title_menu.buttons[0])
	_check(_session.content_version == 27,"independent v27 default")
	var screen := _main.get_node("CounterScreen") as CounterScreen
	var book := screen._social_panel
	install("cotton"); await service()
	_check(_session._day.state.current_night_index == 1 and not _session._day.state.social.introduced,"first-night fixture before faction encounter")
	_check(book._roster.get_child_count() == 0 and book._empty.visible and not book._right.visible,"unmet faction book is empty")
	_check(_find_button(book,"接下采购单") == null and not book._portrait.is_visible_in_tree(),"no tasks or portrait before encounter")
	await _capture("00_empty_book")
	install("preparation"); await receipts()
	screen._close_drawer()
	screen.get_node("%ScreenFlowCoordinator").show_panel(&"day")
	await _frames()
	var day_panel := screen.get_node("Drawer/DrawerColumn/PanelStack/DayFlowPanel") as DayFlowPanel
	_check(not day_panel._description.text.contains("孙大元登门") and not day_panel._description.text.contains("这一带的街面"),"business page excludes introduction dialogue")
	await _capture("00b_second_day_visit")
	await service()
	_check(book._title.text == "采购棉袄" and not book._body.text.contains("说情"),"new procurement copy")
	_check(book._facts.get_children().any(func(n: Node) -> bool: return n is Label and n.text == "奖励"),"offered task shows reward")
	await _capture("01_order")
	_check(not book._scroll.get_v_scroll_bar().visible,"unaccepted order fits")
	var before := JSON.stringify(_session.read_state())
	await _click("打点"); await _click("旧事"); await _click("采购")
	_check(before == JSON.stringify(_session.read_state()),"book browsing is read only")
	install("delivery"); await service()
	await _click("旧事")
	_check(book._body.text.contains("孙大元登门") and book._body.text.contains("这一带的街面，归我管"),"history shows personal bureaucratic introduction")
	_check(book._body.text.contains("孙大元") and book._body.text.contains("完成奖励50银元"),"army history keeps contact and order")
	_check(not book._body.text.contains("临走留下话") and not book._body.text.contains("茶摊的刘婶"),"army history excludes customer reputation and traffic feedback")
	await _capture("02a_army_history")
	await _click("采购")
	_check(book._facts.get_children().any(func(n: Node) -> bool: return n is Label and n.text == "奖励"),"accepted task shows reward")
	_check(book._actions.get_children().filter(func(n: Node) -> bool:return n is CheckBox).size() >= 3,"stock selection available")
	var cash := _session._day.state.cash
	for i in 3:
		var choices := book._actions.get_children().filter(func(n: Node) -> bool:return n is CheckBox)
		await _click_button(choices[i])
	_check(book._selected_coats.size() == 3,"mouse selects exactly three")
	book._scroll.scroll_vertical = 0
	await _frames()
	_check(not book._scroll.get_v_scroll_bar().visible,"three-stock delivery fits without scrolling")
	await _capture("02_delivery_selection")
	var deliver := _find_button(book,"交付所选三件 · 已选3／3")
	_check(deliver != null and not deliver.disabled,"delivery enabled for three")
	if deliver != null: await _click_button(deliver)
	_check(_session._day.state.cash == cash+50 and _session._day.state.social.plaque_awarded,"UI batch grants cash and plaque")
	_check(_find_button(book,"接下采购单") != null,"repeat available immediately")
	await _click("接下采购单")
	_check(not _session._day.state.social.contract.is_empty(),"UI repeat accepted")
	screen._close_drawer(); await _frames()
	var plaque := screen._counter_view.get_hotspot(&"plaque")
	_check(plaque.visible,"plaque physically displayed")
	await _capture("03_plaque_counter")
	await _click_button(plaque)
	_check(book.visible and book.section == 1 and book._body.text.contains("照应牌"),"click plaque opens its effect")
	await _capture("04_plaque_description")
	var escape := InputEventKey.new(); escape.keycode = KEY_ESCAPE; escape.pressed = true; root.push_input(escape)
	await _frames()
	_check(not book.visible and plaque.has_focus(),"Esc returns to plaque")
	install("near_plaque"); await service(); await _click("打点"); await _click("托人送礼")
	_check(_session._day.state.social.plaque_awarded,"gift across threshold grants plaque")
	install("intimidation"); await receipts(); screen._close_drawer(); await _frames()
	screen._route_from_counter(&"trade",&"customer")
	await _frames()
	var trade := _find_trade_panel(_main)
	_check(trade != null,"trade panel")
	var v := _session._counter.customers.active(_session._day.state)
	var asking := v.trade.asking_price
	var reputation: int = _session._day.state.social.reputation
	await _click_button(trade._bargain_toggle)
	await _capture("05_intimidation_option")
	await _click_trade_intent("intimidate","")
	_check(v.trade.asking_price == maxi(1,ceili(asking*.9)) and _session._day.state.social.reputation == reputation-1,"UI intimidation applies once")
	await _capture("06_intimidation_result")
	_check(MilitaryPlaque.used(_session._day.state,v),"UI records threat")
	install("closure"); await service()
	_check(_find_button(_main,"提起旧事，托他说情") == null,"closure favor removed")
	_check(book._actions.get_child_count() == 2,"closure only pay or close")
	await _capture("07_closure")
	install("supply"); await service(); await _capture("08_supply")
	_check(book._title.text == "货源来信","supply preserved")
	install("claim"); await service(); await _capture("09_claim")
	_check(book._title.text == "旧主追索","claim preserved")
	install("cotton"); await receipts(); screen._close_drawer(); await _frames()
	_check(screen._counter_view._item_image.texture != null and screen._counter_view._item_image.texture.resource_path.ends_with("cotton_coat_folded.png"),"folded cotton image shown at counter")
	await _capture("10_cotton_counter")
	print("V27 UI: %d assertions, %d failures" % [_assertions,_failures])
	quit(0 if _failures == 0 else 1)
