extends "res://tests/aqi_investigation_ui.gd"

var aqi_manifest := "res://data/aqi_companion_manifest.json"
var aqi_version := 25
var aqi_fixture_dir := "res://.godot/qa/v25/"

func _run() -> void:
	create_timer(180).timeout.connect(func() -> void: push_error("AQI V25 UI TIMEOUT"); quit(1))
	_capture_prefix = "aqi_v25_1600" if "wide" in OS.get_cmdline_user_args() else "aqi_v25_1280"
	root.size = Vector2i(1600, 900) if "wide" in OS.get_cmdline_user_args() else Vector2i(1280, 720)
	root.content_scale_size = root.size
	root.title = "AQI v25 acceptance " + str(root.size)
	_main = load(ProjectSettings.get_setting("application/run/main_scene")).instantiate()
	_main.get_node("Bootstrap").manifest_path = aqi_manifest
	_main.get_node("Bootstrap").save_path = "res://.godot/qa/v25/ui.json"
	root.add_child(_main)
	_session = _main.get_node("Bootstrap").session
	_check(_session != null, "default loaded")
	if _session == null: quit(1); return
	_session._save.library.path = "res://.godot/qa/v25/ui-library-%d.json" % Time.get_ticks_usec()
	_main.title_menu.configure(true, false)
	driver.check = _check; driver.catalog = _session._counter.catalog
	var screen = _main.get_node("CounterScreen")
	var counter: CounterView = screen._counter_view
	counter_story = counter.story
	var companion: AqiCompanionView = counter.companion
	await _frames()
	await _click_button(_main.title_menu.buttons[0])
	_check(_session.content_version == aqi_version and _session.definition.total_nights == 10, "default v25 ten nights")
	await restore_stage("pre-open-7")
	_check(not counter._portrait.visible and not companion.visible, "preparation no Aqi")
	await _capture("preparation")
	await _click("开铺营业")
	_check(_session.event_model().pending_id == "aq_arrival" and _session.read_state().game_minutes == 0, "opening first visit")
	await _capture("arrival")
	await key(KEY_ESCAPE)
	await _capture("arrival_counter")
	await _click_button(counter._customer_hotspot)
	await narrative_choice("name")
	await narrative_choice("help")
	await narrative_choice("repair")
	await narrative_choice("paper")
	await narrative_choice("bye")
	await narrative_choice("watch")
	_check(not counter.story_active and not companion.visible, "first visit leaves normally")
	await restore_stage("example-aq_stay_8")
	await _capture("request")
	await narrative_choice("careful")
	await narrative_choice("resume")
	_check(companion.visible, "permission enables small companion")
	await restore_stage("idle-8")
	_check(companion.visible and _session.companion_model().available, "idle companion")
	await _capture("idle")
	var original := _session.read_state()
	await _click_button(companion.hotspot)
	_check(companion.dialogue.visible and companion.dialogue._choices.get_child_count() == 3, "three optional topics")
	await _capture("topics")
	await key(KEY_ESCAPE)
	await key(KEY_ENTER)
	_check(root.gui_get_focus_owner() == companion.dialogue._choices.get_child(0), "same menu reopen focuses first option")
	await _click_button(companion.dialogue._choices.get_node("Choice_aq_chat_8"))
	await _click_button(companion.dialogue._choices.get_node("Choice_talk"))
	_check(_session.read_state().event_history.size() == original.event_history.size() + 1 and _session.read_state().game_minutes == original.game_minutes, "one free first chat")
	await _capture("chat_result")
	await key(KEY_ESCAPE)
	_check(not companion.dialogue.visible and root.gui_get_focus_owner() == companion.hotspot, "Esc restores head focus")
	# Keyboard reopens, then business drawer closes this optional conversation.
	await key(KEY_ENTER)
	_check(companion.dialogue.visible, "keyboard opens companion")
	await _click("账本")
	_check(not companion.dialogue.visible and screen.get_node("Drawer").visible, "ledger dismisses chat")
	await key(KEY_ESCAPE)
	await _click_button(companion.hotspot)
	await _click_button(screen.get_node("MenuButton"))
	_check(screen._session_menu.visible and not companion.dialogue.visible, "menu dismisses chat")
	await key(KEY_ESCAPE)
	await restore_stage("customer-8")
	_check(companion.visible and counter._portrait.visible and not _session.companion_model().available, "customer and companion share counter")
	if screen.get_node("Drawer").visible: await key(KEY_ESCAPE)
	await _capture("customer")
	await _click_button(companion.hotspot)
	_check(companion.hint.visible and not companion.dialogue.visible, "busy hint without modal")
	await _capture("busy")
	await restore_stage("idle-9")
	await _click_button(companion.hotspot)
	await _click_button(companion.dialogue._choices.get_node("Choice_aq_paper_9"))
	await _capture("paper_options")
	await _click_button(companion.dialogue._choices.get_node("Choice_bird"))
	await _capture("paper_result")
	await key(KEY_ESCAPE)
	await _click_button(companion.hotspot)
	await _click_button(companion.dialogue._choices.get_node("Choice_aq_leave_9"))
	await _click_button(companion.dialogue._choices.get_node("Choice_leave"))
	_check(not companion.visible and not companion.dialogue.visible, "dismiss leaves no head or dialogue")
	await restore_stage("2155")
	_check(companion.visible, "2155 visible")
	_session.execute("short_task")
	await _frames()
	_check(not companion.visible, "2200 hidden")
	await _capture("2200")
	await restore_stage("example-aq_old_ticket")
	await _capture("old_ticket")
	await narrative_choice("compare")
	_check("七”字的残笔" in counter_story._text.text, "comparison shown")
	await _capture("ticket_comparison")
	await narrative_choice("away")
	await _click("账本")
	var ledger: LedgerPanel = _main.find_child("LedgerPanel", true, false)
	_check(ledger != null, "ledger exists")
	if ledger != null:
		await _click_button(ledger._tabs.get_child(3))
		await _capture("old_affairs")
	await key(KEY_ESCAPE)
	await _click("回房")
	_check(_session.read_state().phase == "private_room", "room after ticket")
	# Frozen old run remains old; title/new restores the configured default.
	var old := JsonContentProvider.new("res://data/aqi_investigation_manifest.json").load_catalog().catalog
	var old_run := old.get_definition("runs", old.default_run_id) as RunDefinition
	var old_store := GhostReplayStore.new(); old_store.origin = {"seed": 42, "run_token": "0123456789abcdef0123456789abcdef"}
	var old_session := RunSession.new(old_run, 24, old_store, old)
	_check(_session._save.library.adopt({"state": old_session._day.state, "run": old_run, "catalog": old}, _session), "old v24 adopted")
	_check(_session.content_version == 24 and _session.companion_model().is_empty(), "old run no companion")
	_main._leave("title"); _main.title_menu.configure(true, false)
	await _frames()
	await _click_button(_main.title_menu.buttons[0])
	_check(_session.content_version == aqi_version, "new default after old game")
	print("AQI V25 UI: %d assertions, %d failures" % [_assertions, _failures])
	quit(0 if _failures == 0 else 1)

func restore_stage(stage: String) -> void:
	var data = JSON.parse_string(FileAccess.get_file_as_string(aqi_fixture_dir + stage + ".json"))
	var codec := SaveCodec.new()
	var state := codec.decode(data, _session.definition, aqi_version, _session._counter.catalog, true)
	_check(state != null, "stage restore " + stage + ": " + codec.error_message)
	if state == null: return
	_check(_session._save.library.adopt({"state": state, "run": _session.definition, "catalog": _session._counter.catalog}, _session), "adopt checkpoint")
	await _frames()
