extends "res://tests/first_debt_durability.gd"
func run() -> void:
	var loaded := JsonContentProvider.new("res://data/first_debt_manifest.json").load_catalog()
	catalog = loaded.catalog; run_def = catalog.get_definition("runs", catalog.default_run_id)
	driver.check = check; driver.catalog = catalog
	for seed_value in 16:
		var first := SevenNightPlan.plan(run_def, catalog, seed_value, 18)
		var extended := SevenNightPlan.plan(run_def, catalog, seed_value, 100)
		check(first == extended.slice(0, 108), "past visitors stable seed%d" % seed_value)
		check(extended.size() == 600 and extended.all(func(r: Dictionary) -> bool: return r.has("person") and not str(r.person.name).is_empty()), "hundred nights named visitors seed%d" % seed_value)
		var short_market := MarketService.plan(run_def, seed_value, 18)
		var long_market := MarketService.plan(run_def, seed_value, 100)
		check(short_market == long_market.slice(0, short_market.size()), "past markets stable")
	var s := load_stage("before-fd_lu")
	var before := s.read_state()
	var visit_statuses: Array = s._day.state.visits.map(func(v: CustomerVisit) -> String: return v.status)
	for step in 3: s.counter_model(); s.first_debt_model(); s.companion_model()
	check(before == s.read_state(), "all read models have no side effects")
	check(s.companion_model().available, "post10 companion available")
	check(s.event_command("fd_aqi_thread", "talk").ok, "new free interaction")
	check(s._day.state.game_minutes == before.game_minutes and s._day.state.visits.map(func(v: CustomerVisit) -> String: return v.status) == visit_statuses, "chat never advances clock or activates visitor")
	var history := s._day.state.event_history.size()
	check(not s.event_command("fd_aqi_thread", "talk").ok and s._day.state.event_history.size() == history, "repeat cannot farm records")
	check(s.event_command("fd_aqi_leave", "bye").ok and not s.companion_model().visible, "dismiss today")
	for cmd in ["close_shop", "wait_until_seal", "resolve_night", "enter_room", "sleep", "finish_sleep", "continue_run", "open_shop"]:
		act(s, cmd); driver.drain(s)
	check(s.companion_model().visible, "returns next night")
	check(s.event_command("fd_aqi_leave", "bye").ok and not s.companion_model().visible, "dismiss uses actual night each time")
	verify(s, "repeat departure")
	s = load_stage("before-fd_lu")
	while s._day.state.game_minutes < 235:
		var v := s._counter.customers.active(s._day.state)
		if v != null: s.counter_command("reject", v.visit_id)
		else: act(s, "short_task")
	check(s.companion_model().visible, "2155 visible")
	act(s, "short_task")
	check(not s.companion_model().visible, "2200 absent")
	# Explicit early close and refused acquisition still offer a contact next night.
	s = load_stage("seller")
	act(s, "close_shop"); act(s, "wait_until_seal"); act(s, "resolve_night"); driver.drain(s)
	for cmd in ["enter_room", "sleep", "finish_sleep", "continue_run", "open_shop"]: act(s, cmd); driver.drain(s)
	check(s._day.state.visits.size() == 6 and s._day.state.visits.any(func(v: CustomerVisit) -> bool: return v.customer_id == "fd_seller"), "missed first seller defers within six ordinary seats")
	check(not FirstDebt.flag(s._day.state, "fd_receipt_read"), "missed seller does not grant evidence")
	s = load_stage("before-fd_family")
	check(s.companion_model().visible and not s.companion_model().available, "Aqi quietly watches a returning Chen meeting")
	check(not s.event_command("fd_aqi_box", "talk").ok, "meeting cannot be bypassed by a direct companion command")
	print("FIRST DEBT EDGES: %d passes, %d failures" % [passes, failures])
	quit(0 if failures == 0 else 1)
