extends SceneTree

var failures := 0
func check(ok: bool, message: String) -> void:
	if not ok:
		failures += 1
		push_error("FAIL: " + message)

func _initialize() -> void:
	# Generated by the preceding M7 write process; never read the player's save.
	var source := "user://tests/m7_cross_process.json"
	var target := "user://tests/m8a_copied_v7.json"
	var source_hash := FileAccess.get_sha256(source)
	check(not source_hash.is_empty(), "generated v7 fixture exists")
	check(DirAccess.copy_absolute(source, target) == OK, "copy valid v7 fixture")
	var catalog := JsonContentProvider.new("res://data/content_manifest.json").load_catalog().catalog
	var definition := catalog.get_definition("runs", catalog.default_run_id) as RunDefinition
	var save := SaveManager.new(target)
	var session := RunSession.new(definition, catalog.content_version, save, catalog)
	check(session.load_checkpoint().ok, "valid copied v7 checkpoint restores")
	check(session.read_state().current_night_index == 2, "copied checkpoint keeps night")
	var before := session.read_state()
	var broken := FileAccess.open(target, FileAccess.WRITE)
	broken.store_string("{broken-save"); broken.close()
	var broken_hash := FileAccess.get_sha256(target)
	check(not session.load_checkpoint().ok, "corrupt copy rejected")
	check(session.read_state() == before, "failed load does not reset progress")
	check(not save.save_state(session._day.state, definition, catalog.content_version), "corrupt copy blocks overwrite")
	check(FileAccess.get_sha256(target) == broken_hash, "corrupt bytes preserved")
	check(FileAccess.get_sha256(source) == source_hash, "original fixture unchanged")
	# Retain copies and hashes in the isolated validation directory for evidence.
	check(DirAccess.copy_absolute(source, "user://tests/m8a_valid_v7.json") == OK, "retain valid copied fixture")
	print("M8A COPY PASS: ", failures == 0, "; source SHA256=", source_hash)
	quit(0 if failures == 0 else 1)
