extends "res://tests/m6_ui_smoke.gd"

func _run() -> void:
	_capture_prefix = "room_1600" if "wide" in OS.get_cmdline_user_args() else "room_1280"
	root.size = Vector2i(1600, 900) if "wide" in OS.get_cmdline_user_args() else Vector2i(1280, 720)
	_main = load("res://scenes/main.tscn").instantiate()
	_main.get_node("Bootstrap").save_path = "user://tests/" + _capture_prefix + ".json"
	root.add_child(_main)
	_session = _main.get_node("Bootstrap").session
	await _frames()
	_check(_session != null and _session.definition.private_room, "房间生产入口")
	if _session == null: quit(1); return
	var helper := RoomTests.new()
	helper._expect = _check
	helper.catalog = _session._counter.catalog
	helper.run_def = _session.definition
	var room := _main.find_child("PrivateRoom", true, false) as PrivateRoomView
	_check(not _main.find_child("CounterView", true, false).get_node("Room").show_life_lamp, "柜台不再绘制命灯")
	for night in 3:
		await _resolve_events()
		await _click("营业")
		await _click("开铺")
		await _click("关门（本夜不可重开）")
		await _click("等到封铺（消耗全部剩余时间）")
		await _click("合上今夜的账册")
		await _click("回房")
		_check(room.is_visible_in_tree() and not _main.find_child("CounterView", true, false).visible, "房间替换柜台")
		var before := _session.read_state()
		await _click("命灯")
		await _click("书桌 · 旧信")
		_check(before == _session.read_state(), "命灯和书桌观察不改变运行")
		if night == 0:
			await _capture("01_letter")
			await _click("床 · 就寝")
			await _capture("02_sleep_confirmation")
			await _click_button(room._confirm.get_cancel_button())
			_check(before == _session.read_state(), "取消就寝不推进")
			await _click("菜单")
			await _click("读取存档")
			var menu := _main.find_child("SessionMenu", true, false) as SessionMenuView
			await _click_button(menu._confirmation.get_ok_button())
			_check(before == _session.read_state(), "实际菜单读取恢复房间")
			var bytes := FileAccess.get_file_as_bytes(_session._save.path)
			var corrupt := FileAccess.open(_session._save.path, FileAccess.WRITE)
			corrupt.store_string("broken-json")
			corrupt.close()
			await _click("菜单")
			await _click("读取存档")
			await _click_button(menu._confirmation.get_ok_button())
			_check(menu._error_dialog.visible and menu._error_dialog.dialog_text.contains("损坏"), "房间读档失败明确提示")
			_check(before == _session.read_state(), "房间读取坏档不改变进度")
			await _click_button(menu._error_dialog.get_ok_button())
			var restored := FileAccess.open(_session._save.path, FileAccess.WRITE)
			restored.store_buffer(bytes)
			restored.close()
		await _click("床 · 就寝")
		await _click_button(room._confirm.get_ok_button())
		_check(_session.read_state().phase == "sleep_resolution", "床确认进入睡眠")
		await _click("等到天明")
		_check(_session.read_state().phase == "day_summary", "睡眠后日结")
		await _click("合卷" if night == 2 else "进入下一夜")
	_check(_session.read_state().phase == "run_ended", "实际输入完成三夜")
	_session.new_run()
	helper.third(_session)
	helper.seal(_session)
	await _frames()
	await _click("低头退开，将红布覆上")
	await _click("回房")
	_check(room.is_visible_in_tree(), "铺内应对后直接引导回房")
	_session.new_run()
	var mirror := helper.midnight(_session)
	_session.risk_command("uncover", mirror)
	_session.mirror_command("midnight_old_ticket", "peek")
	_session.mirror_command("midnight_old_ticket", "pursue")
	_session.risk_command("cover", mirror)
	_session.commerce_command("sell", mirror, "buyer_mirror")
	helper.seal(_session)
	await _frames()
	await _click("回房")
	await _click("命灯")
	await _capture("03_haunting")
	await _click("床 · 就寝")
	await _click_button(room._confirm.get_ok_button())
	_check(_session.read_state().phase == "sleep_resolution" and not _session.read_state().risk_pending.is_empty(), "卖镜后睡眠仍有来客")
	await _capture("04_personal_crisis")
	await _click("垂下眼，护住命灯")
	await _click("等到天明")
	_check(_session.read_state().phase == "day_summary", "房间危机生还后日结")
	await _capture("05_summary")
	_session.new_run()
	mirror = helper.midnight(_session)
	_session.risk_command("uncover", mirror)
	_session.mirror_command("midnight_old_ticket", "peek")
	_session.mirror_command("midnight_old_ticket", "pursue")
	_session.risk_command("cover", mirror)
	helper.seal(_session)
	_session.execute("enter_room")
	_session.execute("sleep")
	await _frames()
	await _click("回头看向身后的人")
	_check(_session.read_state().phase == "dead" and room.visible, "个人死亡留在寝屋")
	_check(room._bed.disabled and room._lamp.disabled and room._desk.disabled and not room._body.text.contains("就寝"), "死亡后观察和就寝关闭，正文与终局一致")
	await _capture("06_death")
	var ending := _session.read_state()
	await _click("菜单")
	await _click("读取存档")
	var menu := _main.find_child("SessionMenu", true, false) as SessionMenuView
	await _click_button(menu._confirmation.get_ok_button())
	_check(ending == _session.read_state(), "真实菜单读取个人死亡不复活或重复归档")
	DirAccess.remove_absolute(ProjectSettings.globalize_path(_session._save.path))
	print("ROOM UI TESTS: %d assertions, %d failures" % [_assertions, _failures])
	quit(0 if _failures == 0 else 1)
